sonar.projectName=Reflet

# Ignore JMH Benchmarks: It is normal that they do not follow standard rules.
# Ignore test fixtures: They are weird on purpose to test edge cases.
# Ignore tests: Due to the nature of reflection programming, it is normal that some "odd" stuff happens in tests.
sonar.exclusions=src/jmh/**,src/test/java/systems/helius/reflet/fixtures/**